---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bit-node-tools
  description: Misc node tools from the Boost Internal Tools team
  annotations:
    github.com/project-slug: ovotech/bit-node-tools
spec:
  owner: boost-bit
  domain: infrastructure-and-enablement
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bit-node-tools
  description: Misc node tools from the Boost Internal Tools team
  annotations:
    github.com/project-slug: ovotech/bit-node-tools
    backstage.io/source-location: url:https://github.com/ovotech/bit-node-tools/tree/main
  tags:
    - internal
    - typescript
spec:
  type: service
  lifecycle: production
  owner: boost-bit
  system: bit-node-tools
